import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./style.css";
import Folders from "./dashboard/folders/page";
import { fetchFolders } from "./lib/data";
import AddNote from "./ui/AddNoteBtn";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "My Note App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const folders = await fetchFolders();
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossOrigin="anonymous" referrerPolicy="no-referrer" />{" "}
            </head>
            <body className={raleway.className}>
                <header>
                    <AddNote />
                </header>
                {children}
            </body>
        </html>
    );
}
