import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Folders from "./folders/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "My Note App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header></header>
                <Folders />
                {children}
            </body>
        </html>
    );
}
